###
GET http://localhost:3000/api/cursos



###FALTA AGREGAR LAS CLAVES FORANEAS DE CREOCURSOS
POST http://localhost:3000/api/cursos
# @name creoCurso
Content-Type: application/json 

{
    "descripcion": "Este curso de Python está diseñado para enseñar a desarrollar aplicaciones robustas y eficientes utilizando uno de los lenguajes de programación más populares y versátiles del mundo.",
    "nombre": "Curso de Python",
    "cantCupos": 25,
    "fechaInicio":"2025-09-03",
    "fechaFin": "2025-10-03",
    "horaInicio": "10:00",
    "horaFin": "13:00",
    "dias": "Viernes",
    "profesorId":2
    
}

### ID
@id = {{creoCurso.response.body.data.id}}

###
GET http://localhost:3000/api/cursos/{{id}}

###
PUT http://localhost:3000/api/cursos/{{id}}
Content-Type: application/json 

{
    "descripcion": "Este curso de HTML enseña a crear y mantener páginas web atractivas y de alta calidad, siguiendo los estándares actuales de la industria.",
    "nombre": "Curso de HTML",
    "cantCupos": 52,
    "duracion": "2 mes",
    "fechaInicio":"17 de febrero de 2025",
    "fechaFin": "17 de abril de 2025",
    "horaInicio": "16:00 hs",
    "horaFin": "18:00 hs",
    "dias": ["Martes"],
    "profesorId":1
}

###
@idToDelete = {{creoCurso.response.body.data.id}}
DELETE http://localhost:3000/api/cursos/{{idToDelete}}

###
PATCH http://localhost:3000/api/cursos/{{idToDelete}}
Content-Type: application/json 

{
    "cantCupos":61
}

###
DELETE http://localhost:3000/api/cursos/{{idToDelete}}

