###
GET http://localhost:3000/api/cursos


###
POST http://localhost:3000/api/cursos
# @name creoCurso
Content-Type: application/json 

{
    "descripcion": "Este curso de javascript enseña a crear y mantener páginas web atractivas y de alta calidad, siguiendo los estándares actuales de la industria.",
    "nombre": "Curso de base de datos",
    "cantCupos": 30,
    "duracion": "3 mes",
    "fechaInicio":"2025-02-02",
    "fechaFin": "2025-04-02",
    "horaInicio": "16:00",
    "horaFin": "18:00",
    "dias": "Martes",
    "profesorId":4
    
}

### 
@id = {{creoCurso.response.body.data.id}}

###
GET http://localhost:3000/api/cursos/6

###
PUT http://localhost:3000/api/cursos/{{id}}
Content-Type: application/json 

{
    "descripcion": "Este curso de HTML enseña a crear y mantener páginas web atractivas y de alta calidad, siguiendo los estándares actuales de la industria.",
    "nombre": "Curso de HTML",
    "cantCupos": 52,
    "duracion": "2 mes",
    "fechaInicio":"2025-02-17",
    "fechaFin": "2025-04-17",
    "horaInicio": "16:00 hs",
    "horaFin": "18:00 hs",
    "dias": ["Martes"],
    "profesorId":1
    
}

###
@idToDelete = {{creoCurso.response.body.data.id}}
DELETE http://localhost:3000/api/cursos/3

###
PATCH http://localhost:3000/api/cursos/{{idToDelete}}
Content-Type: application/json 

{
    "cantCupos":61
}

###
DELETE http://localhost:3000/api/cursos/{{idToDelete}}

