### obtener todos los characters
GET http://localhost:3000/api/certificados


### crear nuevo character
# @name creoCertificado
POST http://localhost:3000/api/certificados
Content-Type: application/json

{
    "descripcion": "Se otorga el siguiente certificado acreditando que el alumno ha asistido al curso de HTML y ha alcanzado los requisitos exigidos por el mismo",
    "fechaEmision": "10 de noviembre de 2024",
    "inscripcionId":1
}

### id
@id = {{creoCertificado.response.body.data.id}}

### obtener un character
GET http://localhost:3000/api/certificados/{{id}}

### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/certificados/{{id}}
Content-Type: application/json

{
    "descripcion": "Se otorga el siguiente certificado acreditando que el alumno ha asistido al curso de Java y ha alcanzado los requisitos exigidos por el mismo",
    "fechaEmision": "05 de agosto de 2024"  
}

### p borrar
# @name creoCertificadoToDelete
POST http://localhost:3000/api/certificados
Content-Type: application/json

{
    "descripcion": "certificado de ...",
    "fechaEmision": "02 de septiembre de 2024"  
}

### borrar un character
@idToDelete = {{creoCertificadoToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/certificados/{{idToDelete}}

### modificar un character (PATCH - parcial)
PATCH http://localhost:3000/api/certificados/{{id}}
Content-Type: application/json

{
    "fechaEmision": "02 de agosto de 2024"
}
