###
GET http://localhost:3000/api/alumnos

###
# @name creoAlumno
POST http://localhost:3000/api/alumnos
Content-Type: application/json 

{
    "nombreCompleto": "Federico Diaz",
    "mail": "fedeprograma@hotmail.com",
    "telefono": "341876098",
    "contrasenia": "capofede11"
}

### id
@id = {{creoAlumno.response.body.data.id}}

###
GET http://localhost:3000/api/alumnos/{{id}}

###
PUT http://localhost:3000/api/alumnos/{{id}}
Content-Type: application/json 

{
    "nombreCompleto": "Juan Francisco Perez",
    "mail": "juan.perez@gmail.com",
    "telefono": "3413645543",
    "contrasenia": "nuevacontra"
}

### p borrar
# @name creoAlumnoToDelete
POST http://localhost:3000/api/alumnos
Content-Type: application/json

{
    "nombreCompleto": "Anchi",
    "mail": "anchi1@gmail.com",
    "telefono": "3412147687",
    "contrasenia": "1234"
}

###
@idToDelete = {{creoAlumnoToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/alumnos/{{idToDelete}}

###
PATCH http://localhost:3000/api/alumnos/{{id}}
Content-Type: application/json 

{
    "telefono":"3413645545"
}
