###
GET http://localhost:3000/api/alumnos

###
GET http://localhost:3000/api/alumnos/a02b91bc-3769-4221-beb1-d7a3aeba7dad

###
POST http://localhost:3000/api/alumnos
Content-Type: application/json 

{
    "nombre_y_apellido": "Federico Diaz",
    "mail": "fedeprograma@hotmail.com",
    "telefono": 3415889546,
    "contrasenia": "capofede11",
}

###
PUT http://localhost:3000/api/alumnos/a02b91bc-3769-4221-beb1-d7a3aeba7dad 
Content-Type: application/json 

{
      'Juan Francisco Perez',
      'juan.perez@gmail.com',
      3413645543,
      'nuevacontra'
}

###
PATCH http://localhost:3000/api/alumnos/a02b91bc-3769-4221-beb1-d7a3aeba7dad 
Content-Type: application/json 

{
    "telefono":3413645545,
}

###
DELETE http://localhost:3000/api/alumnos/a02b91bc-3769-4221-beb1-d7a3aeba7dad