### 
GET http://localhost:3000/api/usuarios

###
GET http://localhost:3000/api/usuarios/1/cursos
### 
# @name creoProfe
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "nombre_y_apellido": "Martin Aguilar",
    "mail": "bob@educatech.com",
    "telefono": "3413456544",
    "contrasenia": "spongebob",
    "cursoId":1
}

###
# @name creoUsuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json 

{
    "nombreCompleto": "Delfina Maurutto",
    "rol":"alumno",
    "mail": "delfi@hotmail.com",
    "telefono": "3413645542",
    "contrasenia": "fdan666"
}

### id
@id = {{creoUsuario.response.body.data.id}}

### id
@mail = {{creoUsuario.response.body.data.mail}}

### 
GET http://localhost:3000/api/usuarios/{{id}}

###
GET  http://localhost:3000/api/usuarios/{{mail}}

### 
PUT http://localhost:3000/api/usuarios/{{id}}
Content-Type: application/json

{
    "nombre_y_apellido": "Matias Maque",
    "mail": "matimaque@hotmail.com",
    "telefono": "3413462154",
    "contrasenia": "mati90000" 
}

### 
# @name creoProfeToDelete
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "nombre_y_apellido": "Dante Aguirre",
    "mail": "danteaguirre@hotmail.com",
    "telefono": "3413456546",
    "contrasenia": "profeddd"
}

### 
DELETE http://localhost:3000/api/usuarios/{{id}}

### modificar un character (PATCH - parcial)
PATCH http://localhost:3000/api/usuarios/{{id}}
Content-Type: application/json

{

    "nombre_y_apellido": "Matias Maque",
    "mail": "matiMaque8@hotmail.com",
    "telefono": "3413462154",
    "contrasenia": "mati90000"
}
