### GET ALL
GET http://localhost:3000/api/tps


### POST 
POST http://localhost:3000/api/tps
# @name createTp
Content-Type: application/json 

{
    "nroTp": 3,
    "consigna": "En este trabajo práctico, crearás un sistema básico de gestión de viajes de colectivos. Este sistema permitirá registrar y manejar la información de los viajes y boletos..",
    "cursoId": 1
    
}

### ID
@id={{createTp.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/tps/{{id}}

###
PUT http://localhost:3000/api/tps/{{id}}
Content-Type: application/json 

{
    "nroTp": 1,
    "consigna": "En este trabajo práctico, se desarrollara un sistema para gestionar el inventario de una librería. El sistema permitirá a los usuarios registrar y actualizar información sobre libros, gestionar las existencias, y generar reportes sobre el inventario.  ",
    "cursoId":3,


}

### POST 2

POST http://localhost:3000/api/tps
# @name createItemToDelete
Content-Type: application/json 

{
    "nroTp": 2,
    "consigna":"consigna 2",
    "curso":null
}

### id2
@idToDelete ={{createItemToDelete.response.body.data.id}}

### DELETE
DELETE http://localhost:3000/api/tps/{{idToDelete}}

###
PATCH http://localhost:3000/api/tps/{{idToDelete}}
Content-Type: application/json 

{
    "consgina": "En este trabajo práctico, se desarrollara un sistema para gestionar el inventario de una librería. El sistema permitirá a los usuarios registrar y actualizar información sobre libros, gestionar las existencias, y generar reportes sobre el inventario.  "
}
