### obtener todos los characters
GET http://localhost:3000/api/tps

### obtener un character
GET http://localhost:3000/api/tps/a678gdab-d307-4221-be5e-f14e43hj5982

### crear nuevo character
POST http://localhost:3000/api/tps
Content-Type: application/json

{
    "consigna": "Desarrolla un programa en Python que actúe como un sistema de gestión para una biblioteca. El sistema debe permitir registrar libros, gestionar préstamos y devoluciones, y realizar búsquedas de libros en el catálogo.
    El objetivo de este trabajo práctico es crear un programa que facilite la administración de una biblioteca pequeña. El sistema debe cubrir las operaciones básicas que se necesitan para manejar el catálogo de libros y los préstamos realizados por los usuarios.",
    "nroTp": 2
}

### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/tps/a678gdab-d307-4221-be5e-f14e43hj5982
Content-Type: application/json

{
    "consigna": "El propósito de este trabajo práctico es desarrollar un programa en Python que facilite la gestión de pedidos en una pequeña tienda. El sistema debe permitir registrar, actualizar, eliminar y consultar pedidos, simplificando así el seguimiento y la administración de las órdenes de compra realizadas por los clientes.
    El sistema que vas a desarrollar actuará como una herramienta de gestión de pedidos para una tienda. Este programa debe proporcionar funcionalidades básicas que permitan a los usuarios manejar eficazmente los pedidos de los clientes.",
    "nroTp": 3  
}

### modificar un character (PATCH - parcial)
PATCH http://localhost:3000/api/tps/a678gdab-d307-4221-be5e-f14e43hj5982
Content-Type: application/json

{
    "nroTp": 1
}

### borrar un character
DELETE http://localhost:3000/api/tps/a678gdab-d307-4221-be5e-f14e43hj5982