###
GET http://localhost:3000/api/inscripciones



###FALTA AGREGAR LAS CLAVES FORANEAS DE CREOINSCRIPCION
POST http://localhost:3000/api/inscripciones
# @name creoInscripcion
Content-Type: application/json 

{
    "fechaInscripcion": "2025-03-27",
    "cancelado": "No",
    "alumnoId":1,
    "cursoId":1
}

### ID
@id = {{creoInscripcion.response.body.data.id}}

###
GET http://localhost:3000/api/inscripciones/{{id}}

###
PUT http://localhost:3000/api/inscripciones/4
Content-Type: application/json 

{
    "fechaInscripcion": "2024-11-11",
    "cancelado": false,
    "alumnoId":1,
    "cursoId":2,
    "certificado": null,
    "rtaparcial": null,
    "rtatp": null
}

###
@idToDelete = {{creoInscripcion.response.body.data.id}}
DELETE http://localhost:3000/api/inscripciones/10

###
PATCH http://localhost:3000/api/inscripciones/{{idToDelete}}
Content-Type: application/json 

{
    "cancelado":true
}

###
DELETE http://localhost:3000/api/inscripciones/{{idToDelete}}

