### 
GET http://localhost:3000/api/profesores


### 
# @name creoProfe
POST http://localhost:3000/api/profesores
Content-Type: application/json

{
    "nombre_y_apellido": "Martin Aguilar",
    "mail": "bob@hotmail.com",
    "telefono": "3413456544",
    "contrasenia": "spongebob",
    "cursoId":3
}

### id
@id = {{creoProfe.response.body.data.id}}

### 
GET http://localhost:3000/api/profesores/{{id}}

### 
PUT http://localhost:3000/api/profesores/{{id}}
Content-Type: application/json

{
    "nombre_y_apellido": "Matias Maque",
    "mail": "matimaque@hotmail.com",
    "telefono": "3413462154",
    "contrasenia": "mati90000" 
}

### 
# @name creoProfeToDelete
POST http://localhost:3000/api/profesores
Content-Type: application/json

{
    "nombre_y_apellido": "Dante Aguirre",
    "mail": "danteaguirre@hotmail.com",
    "telefono": "3413456546",
    "contrasenia": "profeddd"
}

### 
@idToDelete = {{creoProfeToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/profesores/{{idToDelete}}

### modificar un character (PATCH - parcial)
PATCH http://localhost:3000/api/profesores/{{id}}
Content-Type: application/json

{

    "nombre_y_apellido": "Matias Maque",
    "mail": "matiMaque8@hotmail.com",
    "telefono": "3413462154",
    "contrasenia": "mati90000"
}
