### 
GET http://localhost:3000/api/materiales


### 
# @name creoMat
POST http://localhost:3000/api/materiales
Content-Type: application/json

{
    "descripcion": "AAAAAAAAAAAAAAAAAAAAAAAAA ",
    "titulo": "Python. Aplicaciones prácticas",
    "cursoId":6
}

### id
@id = {{creoMat.response.body.data.id}}

### 
GET http://localhost:3000/api/materiales/{{id}}

### 
PUT http://localhost:3000/api/materiales/{{id}}
Content-Type: application/json

{
    "descripcion": "Profundice en el mundo Python y domine los registros",
    "titulo": "Python desde el laboratorio"
}

### 
# @name creoMatToDelete
POST http://localhost:3000/api/materiales
Content-Type: application/json

{
    "descripcion": "Profundice en el mundo Python y domine los registros, los archivos y la programación dinámica En el ámbito de la informática, trabajar con registros y archivos es básico para manejar un lenguaje de programación",
    "titulo": "Python desde el laboratorio nueva edicion"
}

### 
@idToDelete = {{creoMatToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/materiales/1

### 
PATCH http://localhost:3000/api/materiales/{{id}}
Content-Type: application/json

{
 "descripcion": "Este libro proporciona todos los contenidos necesarios para entender qué es el Deep Learning y conocer las posibilidades de esta tecnología",
    "titulo": "Python Deep Learning"
}